server:
  port: 8080
debug: true
spring:
  application:
    name: direct-charge
  datasource:
    url: jdbc:h2:mem:directchargedb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  api-key: ${APP_API_KEY:default-key}

logging:
  level:
    com.itex.directcharge: DEBUG
    org.springframework.web: INFO

itexpay:
  base-url: https://staging.itexpay.com/api/v1
  public-key: ${ITEXPAY_PUBLIC_KEY}
  private-key: ${ITEXPAY_PRIVATE_KEY}
  encryption-key: ${ITEXPAY_ENCRYPTION_KEY}
